name: Sync and Release

on:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: 'tw93/Pake'
        fetch-depth: 0

    - name: Setup Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    - name: Sync fork
      run: |
        git fetch origin main
        git checkout main
        git pull
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Hacksdream/Pake.git main

  build:
    runs-on: windows-latest
    needs: sync
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable-x86_64-msvc
        target: x86_64-pc-windows-msvc
    
    - name: Rusts cache restore
      id: cache_store
      uses: actions/cache/restore@v3
      with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
      key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Config app
      env:
        NAME: PlusAI
        URL: https://cc.plusai.me/
      run: |
        npm install
        npm run build:config

    - name: Build and package app
      run: |
        npm run tauri build -- --target x86_64-pc-windows-msvc
        New-Item -Path "output\windows" -ItemType Directory
        Move-Item -Path "src-tauri\target\x86_64-pc-windows-msvc\release\bundle\msi\*.msi" -Destination "output\windows\${{inputs.title}}_x64.msi"
    
    - name: Restore Cargo Lock File
      run: |
        git checkout -- src-tauri/Cargo.lock
    
    - name: Rust cache store
      uses: actions/cache/save@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          src-tauri/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Upload For Single Build
      uses: actions/upload-artifact@v3
      if: startsWith(github.ref, 'refs/tags/') != true
      with:
        path: 'output/*/*.*'

    - name: Upload For Release
      # arg info: https://github.com/ncipollo/release-action#release-action
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/') == true
      with:
        allowUpdates: true
        artifacts: 'output/*/*.*'
        token: ${{ secrets.GITHUB_TOKEN }}
