name: Sync and Release

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  sync_with_upstream:
    name: Sync with Upstream
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
        - name: Checkout target repo
          uses: actions/checkout@v3

        - name: Sync Upstream
          uses: TG908/fork-sync@v1.6.3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            owner: tw93 # fork 的上游仓库 user
            head: main # fork 的上游仓库 branch
            base: main # 本地仓库 branch
        

  build:
    runs-on: windows-latest
    needs: sync_with_upstream

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable-x86_64-msvc
        target: x86_64-pc-windows-msvc
    
    - name: Rusts cache restore
      id: cache_store
      uses: actions/cache/restore@v3
      with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
    
    - name: Config app
      env:
        NAME: PlusAI
        URL: https://cc.plusai.me/
      run: |
        npm install
        npm run build:config

    - name: Build and package app
      run: |
        npm run tauri build -- --target x86_64-pc-windows-msvc
        New-Item -Path "output\windows" -ItemType Directory
        Move-Item -Path "src-tauri\target\x86_64-pc-windows-msvc\release\bundle\msi\*.msi" -Destination "output\windows\${{inputs.title}}_x64.msi"
    
    - name: Restore Cargo Lock File
      run: |
        git checkout -- src-tauri/Cargo.lock
    
    - name: Rust cache store
      uses: actions/cache/save@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          src-tauri/target/

    - name: Upload For Single Build
      uses: actions/upload-artifact@v3
      if: startsWith(github.ref, 'refs/tags/') != true
      with:
        path: 'output/*/*.*'

    - name: Upload For Release
      # arg info: https://github.com/ncipollo/release-action#release-action
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/') == true
      with:
        allowUpdates: true
        artifacts: 'output/*/*.*'
        token: ${{ secrets.GITHUB_TOKEN }}
